# Generated by Django 5.2.4 on 2025-07-31 05:41

from django.db import migrations


def create_default_categories(apps, schema_editor):
    Category = apps.get_model('api', 'Category')
    
    default_categories = [
        {
            'name': 'Food & Dining',
            'description': 'Restaurants, groceries, and dining expenses',
            'color': '#10B981',
            'icon': 'utensils'
        },
        {
            'name': 'Transportation',
            'description': 'Gas, public transport, and vehicle expenses',
            'color': '#3B82F6',
            'icon': 'car'
        },
        {
            'name': 'Shopping',
            'description': 'Clothing, electronics, and general shopping',
            'color': '#F59E0B',
            'icon': 'shopping-bag'
        },
        {
            'name': 'Entertainment',
            'description': 'Movies, games, and leisure activities',
            'color': '#8B5CF6',
            'icon': 'film'
        },
        {
            'name': 'Healthcare',
            'description': 'Medical expenses and healthcare costs',
            'color': '#EF4444',
            'icon': 'heart'
        },
        {
            'name': 'Utilities',
            'description': 'Electricity, water, internet, and phone bills',
            'color': '#06B6D4',
            'icon': 'zap'
        },
        {
            'name': 'Housing',
            'description': 'Rent, mortgage, and home maintenance',
            'color': '#84CC16',
            'icon': 'home'
        },
        {
            'name': 'Education',
            'description': 'Books, courses, and educational expenses',
            'color': '#F97316',
            'icon': 'book'
        },
        {
            'name': 'Travel',
            'description': 'Vacations, flights, and travel expenses',
            'color': '#EC4899',
            'icon': 'plane'
        },
        {
            'name': 'Other',
            'description': 'Miscellaneous and other expenses',
            'color': '#6B7280',
            'icon': 'more-horizontal'
        }
    ]
    
    for category_data in default_categories:
        Category.objects.get_or_create(
            name=category_data['name'],
            defaults=category_data
        )


def remove_default_categories(apps, schema_editor):
    Category = apps.get_model('api', 'Category')
    Category.objects.filter(name__in=[
        'Food & Dining', 'Transportation', 'Shopping', 'Entertainment',
        'Healthcare', 'Utilities', 'Housing', 'Education', 'Travel', 'Other'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, remove_default_categories),
    ]
